# Generated by Django 2.1.7 on 2019-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Женский'), (2, 'Мужской'), (3, 'Ребенок')], verbose_name='Пол'),
        ),
    ]
